name: TaskFlowApp
options:
  bundleIdPrefix: com.seuusuario
  deploymentTarget:
    iOS: '12.0'
workspace:
  name: TaskFlowApp
  projects:
    - TaskFlowApp.xcodeproj

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.6.0

targets:
  TaskFlowApp:
    type: application
    platform: iOS
    sources: [TaskFlowApp/Sources]
    resources: [TaskFlowApp/Resources]
    dependencies:
      - target: TaskFlowModule
      - target: SettingsModule

  TaskFlowModule:
    type: framework
    platform: iOS
    sources: [TaskFlowModule/Sources]
    dependencies:
      - package: SnapKit

  SettingsModule:
    type: framework
    platform: iOS
    sources: [SettingsModule/Sources]
